name: Coverage

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
          contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tox
        run: pip install tox

      - name: Run tests with coverage
        run: tox -e coverage

      - name: Creating coverage folder
        run: |
          mkdir -p coverage

      - name: Coverage Badge
        uses: tj-actions/coverage-badge-py@v1.8
        with:
          output: coverage/coverage.svg

      - name: Publish coverage report to coverage-badge branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: coverage-badge
          folder: coverage